import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
size = 14
normal.family = "VictorMono NFM"
bold.family = "VictorMono NFM"
italic.family = "VictorMono NFM"
italic.style = "Oblique"
bold_italic.family = "VictorMono NFM"
